# Generated by Django 5.0.3 on 2024-10-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cartitems_cart'),
        ('products', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon'),
        ),
    ]
