# Generated by Django 5.0.3 on 2024-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_coupan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupan',
            new_name='coupon',
        ),
    ]
