# Generated by Django 5.1 on 2024-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(),
        ),
    ]
