# Generated by Django 5.1 on 2024-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_colorvariant_price_alter_sizevariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_name',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
    ]
